<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Yogeshs-MBP" failures="1" tests="4" name="Create Customer API" time="4.187" errors="0" timestamp="2021-11-24T15:46:11 CET">
  <testcase classname="APITestCases.CreateCustomerPostReqTest" name="validateCreateCustomerAPIWithValidSecretKey" time="2.056"/>
  <testcase classname="APITestCases.CreateCustomerPostReqTest" name="validateCreateCustomerAPIWithValidSecretKey" time="0.646"/>
  <testcase classname="APITestCases.CreateCustomerPostReqTest" name="validateCreateCustomerAPIWithValidSecretKey" time="0.711"/>
  <testcase classname="APITestCases.DeleteCustomerTest" name="deleteCustomer" time="0.508">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at APITestCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="SetupPackage.base" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="SetupPackage.base" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Create Customer API -->
